export const pagination = [
  {
    id: 1,
    current: true,
    ellipsis: false,
  },
  {
    id: 2,
    current: false,
    ellipsis: false,
  },
  {
    id: 3,
    current: false,
    ellipsis: true,
  },
  {
    id: 4,
    current: false,
    ellipsis: false,
  },
]

export const country = [
  {
    domains: ['uap-bd.edu'],
    web_pages: ['http://www.uap-bd.edu/'],
    name: 'University of Asia Pacific, Dhanmondi',
    alpha_two_code: 'BD',
    'state-province': null,
    country: 'Bangladesh',
  },
  {
    domains: ['bac.edu.my'],
    web_pages: ['http://www.bac.edu.my/'],
    name: 'Brickfields Asia College',
    alpha_two_code: 'MY',
    'state-province': null,
    country: 'Malaysia',
  },
  {
    domains: ['tiaa.edu.ge'],
    web_pages: ['http://www.tiaa.edu.ge/'],
    name: 'Tbilisi Institute of Asia and Africa',
    alpha_two_code: 'GE',
    'state-province': null,
    country: 'Georgia',
  },
  {
    domains: ['auca.kg'],
    web_pages: ['http://www.auca.kg/'],
    name: 'American University of Central Asia',
    alpha_two_code: 'KG',
    'state-province': null,
    country: 'Kyrgyzstan',
  },
  {
    domains: ['newasia.bj.edu.cn'],
    web_pages: ['http://www.newasia.bj.edu.cn/'],
    name: 'Beijing New Asia University',
    alpha_two_code: 'CN',
    'state-province': null,
    country: 'China',
  },
  {
    domains: ['toua-u.ac.jp'],
    web_pages: ['http://www.toua-u.ac.jp/'],
    name: 'University of East Asia',
    alpha_two_code: 'JP',
    'state-province': null,
    country: 'Japan',
  },
  {
    domains: ['apu.ac.jp'],
    web_pages: ['http://www.apu.ac.jp/'],
    name: 'Ritsumeikan Asia Pacific University',
    alpha_two_code: 'JP',
    'state-province': null,
    country: 'Japan',
  },
  {
    domains: ['sau.ac.th'],
    web_pages: ['https://www.sau.ac.th/'],
    name: 'South-East Asia University',
    alpha_two_code: 'TH',
    'state-province': 'Bangkok',
    country: 'Thailand',
  },
  {
    domains: ['eau.ac.th'],
    web_pages: ['https://www.eau.ac.th/'],
    name: 'Eastern Asia University',
    alpha_two_code: 'TH',
    'state-province': 'Pathum Thani',
    country: 'Thailand',
  },
  {
    domains: ['usa.edu.pk'],
    web_pages: ['http://www.usa.edu.pk/'],
    name: 'University of South Asia',
    alpha_two_code: 'PK',
    'state-province': null,
    country: 'Pakistan',
  },
  {
    domains: ['uap.edu.ph'],
    web_pages: ['http://www.uap.edu.ph/'],
    name: 'University of Asia and the Pacific',
    alpha_two_code: 'PH',
    'state-province': null,
    country: 'Philippines',
  },
  {
    domains: ['asia-u.ac.jp'],
    web_pages: ['http://www.asia-u.ac.jp/'],
    name: 'Asia University',
    alpha_two_code: 'JP',
    'state-province': null,
    country: 'Japan',
  },
  {
    domains: ['apiit.edu.my'],
    web_pages: ['http://www.apiit.edu.my/'],
    name: 'Asia Pacific Institute of Information Technology (APIIT)',
    alpha_two_code: 'MY',
    'state-province': null,
    country: 'Malaysia',
  },
  {
    domains: ['aeu.edu.kh'],
    web_pages: ['http://www.aeu.edu.kh/'],
    name: 'Asia Europe University',
    alpha_two_code: 'KH',
    'state-province': null,
    country: 'Cambodia',
  },
  {
    domains: ['aeu.edu.my'],
    web_pages: ['http://www.aeu.edu.my/'],
    name: 'Asia E University',
    alpha_two_code: 'MY',
    'state-province': null,
    country: 'Malaysia',
  },
  {
    domains: ['auca.kg'],
    web_pages: ['http://www.auca.kg/'],
    name: 'American University of Central Asia',
    alpha_two_code: 'KG',
    'state-province': null,
    country: 'Kyrgyzstan',
  },
  {
    domains: ['eau.ac.th'],
    web_pages: ['https://www.eau.ac.th/'],
    name: 'Eastern Asia University',
    alpha_two_code: 'TH',
    'state-province': 'Pathum Thani',
    country: 'Thailand',
  },
  {
    domains: ['sau.ac.th'],
    web_pages: ['https://www.sau.ac.th/'],
    name: 'South-East Asia University',
    alpha_two_code: 'TH',
    'state-province': 'Bangkok',
    country: 'Thailand',
  },
  {
    domains: ['apu.ac.jp'],
    web_pages: ['http://www.apu.ac.jp/'],
    name: 'Ritsumeikan Asia Pacific University',
    alpha_two_code: 'JP',
    'state-province': null,
    country: 'Japan',
  },
  {
    domains: ['bac.edu.my'],
    web_pages: ['http://www.bac.edu.my/'],
    name: 'Brickfields Asia College',
    alpha_two_code: 'MY',
    'state-province': null,
    country: 'Malaysia',
  },
  {
    domains: ['uap.edu.ph'],
    web_pages: ['http://www.uap.edu.ph/'],
    name: 'University of Asia and the Pacific',
    alpha_two_code: 'PH',
    'state-province': null,
    country: 'Philippines',
  },
  {
    domains: ['usa.edu.pk'],
    web_pages: ['http://www.usa.edu.pk/'],
    name: 'University of South Asia',
    alpha_two_code: 'PK',
    'state-province': null,
    country: 'Pakistan',
  },
  {
    domains: ['toua-u.ac.jp'],
    web_pages: ['http://www.toua-u.ac.jp/'],
    name: 'University of East Asia',
    alpha_two_code: 'JP',
    'state-province': null,
    country: 'Japan',
  },
  {
    domains: ['uap-bd.edu'],
    web_pages: ['http://www.uap-bd.edu/'],
    name: 'University of Asia Pacific, Dhanmondi',
    alpha_two_code: 'BD',
    'state-province': null,
    country: 'Bangladesh',
  },
  {
    domains: ['newasia.bj.edu.cn'],
    web_pages: ['http://www.newasia.bj.edu.cn/'],
    name: 'Beijing New Asia University',
    alpha_two_code: 'CN',
    'state-province': null,
    country: 'China',
  },
  {
    domains: ['tiaa.edu.ge'],
    web_pages: ['http://www.tiaa.edu.ge/'],
    name: 'Tbilisi Institute of Asia and Africa',
    alpha_two_code: 'GE',
    'state-province': null,
    country: 'Georgia',
  },
  {
    domains: ['southasianuniversity.org'],
    web_pages: ['http://www.southasianuniversity.org/'],
    name: 'South Asian University',
    alpha_two_code: 'IN',
    'state-province': null,
    country: 'India',
  },
  {
    domains: ['saitm.edu.lk'],
    web_pages: ['http://www.saitm.edu.lk/'],
    name: 'South Asian Institute of Technology And Medicine (SAITM)',
    alpha_two_code: 'LK',
    'state-province': null,
    country: 'Sri Lanka',
  },
  {
    domains: ['acts.ac.kr'],
    web_pages: ['http://www.acts.ac.kr/'],
    name: 'Asian United Theological University',
    alpha_two_code: 'KR',
    'state-province': null,
    country: 'Korea, Republic of',
  },
  {
    domains: ['efau.org'],
    web_pages: ['http://www.asianu.ac.th/'],
    name: 'Asian University',
    alpha_two_code: 'TH',
    'state-province': 'Chon Buri',
    country: 'Thailand',
  },
  {
    domains: ['aub-bd.org'],
    web_pages: ['http://www.aub-bd.org/'],
    name: 'Asian University of Bangladesh',
    alpha_two_code: 'BD',
    'state-province': null,
    country: 'Bangladesh',
  },
  {
    domains: ['asianust.ac.th'],
    web_pages: ['http://www.asianust.ac.th/'],
    name: 'Asian University of Science and Technology',
    alpha_two_code: 'TH',
    'state-province': 'Chon Buri',
    country: 'Thailand',
  },
  {
    domains: ['ait.ac.th'],
    web_pages: ['https://www.ait.ac.th/'],
    name: 'Asian Institute of Technology',
    alpha_two_code: 'TH',
    'state-province': 'Pathum Thani',
    country: 'Thailand',
  },
  {
    domains: ['asmi.edu.kg'],
    web_pages: ['http://www.asmi.edu.kg/'],
    name: 'Asian Medical Institute',
    alpha_two_code: 'KG',
    'state-province': null,
    country: 'Kyrgyzstan',
  },
  {
    domains: ['southasianuniversity.org'],
    web_pages: ['http://www.southasianuniversity.org/'],
    name: 'South Asian University',
    alpha_two_code: 'IN',
    'state-province': null,
    country: 'India',
  },
  {
    domains: ['saitm.edu.lk'],
    web_pages: ['http://www.saitm.edu.lk/'],
    name: 'South Asian Institute of Technology And Medicine (SAITM)',
    alpha_two_code: 'LK',
    'state-province': null,
    country: 'Sri Lanka',
  },
]
